services:
  db:
    image: mariadb
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cs340_maluskid
      MYSQL_USER: maluskid
      MYSQL_PASSWORD: domin8or
    ports:
      - '8080:8080'
    volumes: 
      - db_data:/var/lib/mysql

volumes:
  db_data:

